<?php
   switch($lng) {
      case 'eng':
         define('_TITLE', 'EMS JSC - Transparency Platform');
         define('_SELECT_DAY', 'Select day');
         define('_DAY', 'Day');
         define('_HINT_TABLE', 'Table');
         define('_HINT_CHART', 'Chart');
         define('_HINT_DOWNLOAD', 'Download');
         define('_RESULTS', 'Balancing energy and settlement price ');
         define('_HOUR', 'Hour');
         define('_DOWNLOAD_DATA', 'Download data');
         define('_TITLE_1', 'Select day and report type');
         define('_TITLE_2', 'Select day');
         define('_TITLE_3', 'Select report type');
         define('_MSG_SELECT_DAY', 'Click on \"Day\" to select date.');
         define('_MSG_SELECT_REPORT', 'Click on \"Report\" to select report type.');
         define('_DAY_SELECTED', 'Day selected: ');
         define('_REPORT_SELECTED', 'Report type selected: ');
         define('_REPORT', 'Report');
         define('_SELECT_REPORT', 'Select report');
         define('_TYPE_PRELIMINARY', 'Preliminary');
         define('_TYPE_FINAL', 'Final');
         define('_NO_DATA_PREF', ' report for: ');
         define('_NO_DATA_SUF', ' is not available.');
         define('_INTERVAL', 'Accounting interval');
         define('_ENERGY_SECONDARY', 'Balancing energy due to the engagement of SECONDARY control');
         define('_ENERGY_TERTIARY', 'Balancing energy due to the engagement of TERTIARY control');
         define('_ENERGY_ACCIDENTAL', 'EMERGENCY balancing energy');
         define('_PRICE_SETTLEMENT', 'IMBALANCE SETTLEMENT PRICE for balancing group deviation accounting');
         define('_PRICE', 'Price');
         define('_PRICE_WEIGHTED', 'Weighted price');
         define('_SUM', 'Total');
         define('_INTERVAL_BEGIN', 'Start');
         define('_INTERVAL_END', 'End');
         define('_NOTE', 'Note:<br>The + sign indicates involvement of balancing energy upwards and engagement of emergency energy in the direction of import<br>The - sign indicates involvement of balancing energy down and engagement of emergency energy in the direction of export<br>Imbalance settlement price is calculated in accordance with Market code');
         define('_CHART_1_TITLE', 'Total balancing energy');
         define('_CHART_2_TITLE', 'Settlement price');
         define('_UPWARD', 'UPWARD');
         define('_DOWNWARD', 'DOWNWARD');
         break;
      case 'lat':
         define('_TITLE', 'EMS AD - Platforma za transparentnost');
         define('_SELECT_DAY', 'Izaberi dan');
         define('_DAY', 'Dan');
         define('_HINT_TABLE', 'Tabelarni prikaz');
         define('_HINT_CHART', 'Grafički prikaz');
         define('_HINT_DOWNLOAD', 'Preuzimanje podataka');
         define('_RESULTS', 'Angažovana balansna energija i cena poravnanja');
         define('_HOUR', 'Sat');
         define('_DOWNLOAD_DATA', 'Preuzimanje podataka');
         define('_TITLE_1', 'Izaberite dan i tip izveštaja');
         define('_TITLE_2', 'Izaberite dan');
         define('_TITLE_3', 'Izaberite tip izveštaja');
         define('_MSG_SELECT_DAY', 'Kliknite na \"Dan\" za izbor dana.');
         define('_MSG_SELECT_REPORT', 'Kliknite na \"Izveštaj\" za izbor tipa izveštaja.');
         define('_DAY_SELECTED', 'Izabran je dan: ');
         define('_REPORT_SELECTED', 'Izabran je tip izveštaja: ');
         define('_REPORT', 'Izveštaj');
         define('_SELECT_REPORT', 'Izaberi izveštaj');
         define('_TYPE_PRELIMINARY', 'Preliminarni');
         define('_TYPE_FINAL', 'Konačni');
         define('_NO_DATA_PREF', 'Nije kreiran');
         define('_NO_DATA_SUF', ' izveštaj za dan: ');
         define('_INTERVAL', 'Obračunski interval (OI)');
         define('_ENERGY_SECONDARY', 'Angažovana balansna energija usled angažovanja SEKUNDARNE regulacije');
         define('_ENERGY_TERTIARY', 'Angažovana balansna energija usled angažovanja TERCIJARNE regulacije');
         define('_ENERGY_ACCIDENTAL', 'Angažovana HAVARIJSKA balansna energija');
         define('_PRICE_SETTLEMENT', 'CENA PORAVNANJA<br>za obračun odstupanja balansnih grupa');
         define('_PRICE', 'Cena');
         define('_PRICE_WEIGHTED', 'Ponderisana cena');
         define('_SUM', 'Ukupno');
         define('_INTERVAL_BEGIN', 'Početak');
         define('_INTERVAL_END', 'Kraj ');
         define('_NOTE', 'NAPOMENA:<br>Predznak \"+\" označava angažovanje balansne energije naviše i angažovanje havarijske energije u smeru uvoza.<br>Predznak \"-\" označava angažovanje balansne energije naniže i angažovanje havarijske energije u smeru izvoza.<br>Cena poravnanja se računa u skladu sa Pravilima o radu tržišta električne energije. ');
         define('_CHART_1_TITLE', 'Ukupna angažovana balansna energija ');
         define('_CHART_2_TITLE', 'Cena poravnanja ');
         define('_UPWARD', 'NAVIŠE');
         define('_DOWNWARD', 'NANIŽE');
         break;
      case 'cir':
         define('_TITLE', 'ЕМС АД - Платформа за транспарентност');
         define('_SELECT_DAY', 'Изабери дан');
         define('_DAY', 'Дан');
         define('_HINT_TABLE', 'Табеларни приказ');
         define('_HINT_CHART', 'Графички приказ');
         define('_HINT_DOWNLOAD', 'Преузимање података');
         define('_RESULTS', 'Ангажована балансна енергија и цена поравнања');
         define('_HOUR', 'Сат');
         define('_DOWNLOAD_DATA', 'Преузимање података');
         define('_TITLE_1', 'Изаберите дан и тип извештаја');
         define('_TITLE_2', 'Изаберите дан');
         define('_TITLE_3', 'Изаберите тип извештаја');
         define('_MSG_SELECT_DAY', 'Кликните на \"Дан\" за избор дана.');
         define('_MSG_SELECT_REPORT', 'Кликните на \"Извештај\" за избор типа извештаја.');
         define('_DAY_SELECTED', 'Изабран је дан: ');
         define('_REPORT_SELECTED', 'Изабран је тип извештаја: ');
         define('_REPORT', 'Извештај');
         define('_SELECT_REPORT', 'Изабери извештај');
         define('_TYPE_PRELIMINARY', 'Прелиминарни');
         define('_TYPE_FINAL', 'Коначни');
         define('_NO_DATA_PREF', 'Није креиран');
         define('_NO_DATA_SUF', ' извештај за дан: ');
         define('_INTERVAL', 'Обрачунски интервал (ОИ)');
         define('_ENERGY_SECONDARY', 'Ангажована балансна енергија услед ангажовања СЕКУНДАРНЕ регулације');
         define('_ENERGY_TERTIARY', 'Ангажована балансна енергија услед ангажовања ТЕРЦИЈАРНЕ регулације');
         define('_ENERGY_ACCIDENTAL', 'Ангажована ХАВАРИЈСКА балансна енергија');
         define('_PRICE_SETTLEMENT', 'ЦЕНА ПОРАВНАЊА<br>за обрачун одступања балансних група');
         define('_PRICE', 'Цена');
         define('_PRICE_WEIGHTED', 'Пондерисана цена');
         define('_SUM', 'Укупно');
         define('_INTERVAL_BEGIN', 'Почетак');
         define('_INTERVAL_END', 'Крај ');
         define('_NOTE', 'НАПОМЕНА:<br>Предзнак \"+\" означава ангажовање балансне енергије навише и ангажовање хаваријске енергије у смеру увоза.<br>Предзнак \"-\" означава ангажовање балансне енергије наниже и ангажовање хаваријске енергије у смеру извоза.<br>Цена поравнања се рачуна у складу са Правилима о раду тржишта електричне енергије. ');
         define('_CHART_1_TITLE', 'Укупна ангажована балансна енергија ');
         define('_CHART_2_TITLE', 'Цена поравнања ');
         define('_UPWARD', 'НАВИШЕ');
         define('_DOWNWARD', 'НАНИЖЕ');
         break;
   }
?>
